weights: ''
cfg: cfg/yolov4-tiny-relu.cfg
data: ./data/coco.yaml
hyp: data/hyp.scratch.yaml
epochs: 300
batch_size: 64
img_size:
- 640
- 640
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
device: '0'
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
log_imgs: 16
workers: 8
project: runs/train
name: yolov4-pacsp
exist_ok: false
amp: false
grow_prune: true
channel_sparsity: 0.5
init_channel_ratio: 0.2
delta_T: 2
T_max: 470
total_batch_size: 64
world_size: 1
global_rank: -1
save_dir: runs/train/yolov4-pacsp4
